[build]
  command = "npm run build"
  publish = "build/client"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["build/server/**", "node_modules/@react-router/**"]
